self.addEventListener("install",e=>{
e.waitUntil(
caches.open("storecat").then(c=>c.addAll([
"/","/landing.html","/login.html",
"/css/style.css","/js/app.js"
]))
)});
self.addEventListener("fetch",e=>{
e.respondWith(caches.match(e.request).then(r=>r||fetch(e.request)))
});
